### ISSUE TITLE
Consider disallowing the use of literal string as callback in Lodash functions

### ISSUE THREAD

**Issue by PinkChampagne17** [RightCapitalHQ/frontend-style-guide#171]
## Description
Lodash allows the use of string literals to specify properties in methods like `_.map`. Although convenient, this can result in less maintainable code. We propose disallowing this practice in favor of explicit callback functions.

## Rationale

- Static Analysis: Improves code analysis and error detection.
- Type Safety: Callback functions allow for better type checking.

## Example

```javascript
// ❌ Incorrect
_.map(students, "age")

// ✅ Correct
_.map(students, student => student.age)
```

**Comment by frantic1048** [comment]
We may make use of this rule:

https://github.com/wix-incubator/eslint-plugin-lodash/blob/master/docs/rules/prop-shorthand.md#property-shorthand

**Comment by frantic1048** [comment]
For similar reason, the `lodash/matches-shorthand` rule may also be considered:
https://github.com/wix-incubator/eslint-plugin-lodash/blob/master/docs/rules/matches-shorthand.md

**Comment by PinkChampagne17** [comment]
> For similar reason, the `lodash/matches-shorthand` rule may also be considered: [wix-incubator/eslint-plugin-lodash@`master`/docs/rules/matches-shorthand.md](https://github.com/wix-incubator/eslint-plugin-lodash/blob/master/docs/rules/matches-shorthand.md?rgh-link-date=2024-07-15T06%3A32%3A37Z)

The matches shorthand is type-safe and can be analyzed statically, so, I don't think we need to consider this rule.
